# Generated by Django 2.1.7 on 2019-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_auto_20190305_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='files',
            field=models.FileField(null=True, upload_to='myblog/%Y/%m/%d'),
        ),
    ]
